<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'Finland', 'code' => 'FIN'],
            ['name' => 'United States', 'code' => 'USA'],
            ['name' => 'Canada', 'code' => 'CAN'],
            ['name' => 'United Kingdom', 'code' => 'GBR'],
            ['name' => 'Germany', 'code' => 'DEU'],
            ['name' => 'France', 'code' => 'FRA'],
            ['name' => 'Italy', 'code' => 'ITA'],
            ['name' => 'Spain', 'code' => 'ESP'],
            ['name' => 'Netherlands', 'code' => 'NLD'],
            ['name' => 'Belgium', 'code' => 'BEL'],
            ['name' => 'Sweden', 'code' => 'SWE'],
            ['name' => 'Switzerland', 'code' => 'CHE'],
            ['name' => 'Austria', 'code' => 'AUT'],
            ['name' => 'Denmark', 'code' => 'DNK'],
            ['name' => 'Norway', 'code' => 'NOR'],
            ['name' => 'Ireland', 'code' => 'IRL'],
            ['name' => 'Portugal', 'code' => 'PRT'],
            ['name' => 'Greece', 'code' => 'GRC'],
            ['name' => 'Luxembourg', 'code' => 'LUX'],
            ['name' => 'Iceland', 'code' => 'ISL'],
            ['name' => 'Poland', 'code' => 'POL'],
            ['name' => 'Czech Republic', 'code' => 'CZE'],
            ['name' => 'Hungary', 'code' => 'HUN'],
            ['name' => 'Romania', 'code' => 'ROU'],
            ['name' => 'Slovakia', 'code' => 'SVK'],
            ['name' => 'Slovenia', 'code' => 'SVN'],
            ['name' => 'Croatia', 'code' => 'HRV'],
            ['name' => 'Estonia', 'code' => 'EST'],
            ['name' => 'Latvia', 'code' => 'LVA'],
            ['name' => 'Lithuania', 'code' => 'LTU'],
            ['name' => 'Belarus', 'code' => 'BLR'],
            ['name' => 'Ukraine', 'code' => 'UKR'],
            ['name' => 'Moldova', 'code' => 'MDA'],
            ['name' => 'Bulgaria', 'code' => 'BGR'],
            ['name' => 'Albania', 'code' => 'ALB'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BIH'],
            ['name' => 'Serbia', 'code' => 'SRB'],
            ['name' => 'Montenegro', 'code' => 'MNE'],
            ['name' => 'Kosovo', 'code' => 'KSV'],
            ['name' => 'Macedonia', 'code' => 'MKD'],
            ['name' => 'Georgia', 'code' => 'GEO'],
            ['name' => 'Armenia', 'code' => 'ARM'],
            ['name' => 'Azerbaijan', 'code' => 'AZE'],
            ['name' => 'Turkey', 'code' => 'TUR'],
            ['name' => 'Pakistan', 'code' => 'PAK'],
            ['name' => 'India', 'code' => 'IND'],
            ['name' => 'Bangladesh', 'code' => 'BGD'],
            ['name' => 'Afghanistan', 'code' => 'AFG'],
            ['name' => 'Sri Lanka', 'code' => 'LKA'],
            ['name' => 'Myanmar', 'code' => 'MMR'],
            ['name' => 'Nepal', 'code' => 'NPL'],
            ['name' => 'Bhutan', 'code' => 'BTN'],
            ['name' => 'Maldives', 'code' => 'MDV'],
            ['name' => 'China', 'code' => 'CHN'],
            ['name' => 'Japan', 'code' => 'JPN'],
            ['name' => 'South Korea', 'code' => 'KOR'],
            ['name' => 'North Korea', 'code' => 'PRK'],
            ['name' => 'Mongolia', 'code' => 'MNG'],
            ['name' => 'Taiwan', 'code' => 'TWN'],
            ['name' => 'Hong Kong', 'code' => 'HKG'],
            ['name' => 'Macau', 'code' => 'MAC'],
            ['name' => 'Thailand', 'code' => 'THA'],
            ['name' => 'Vietnam', 'code' => 'VNM'],
            ['name' => 'Cambodia', 'code' => 'KHM'],
            ['name' => 'Laos', 'code' => 'LAO'],
            ['name' => 'Malaysia', 'code' => 'MYS'],
            ['name' => 'Singapore', 'code' => 'SGP'],
            ['name' => 'Indonesia', 'code' => 'IDN'],
            ['name' => 'Philippines', 'code' => 'PHL'],
            ['name' => 'Brunei', 'code' => 'BRN'],
            ['name' => 'East Timor', 'code' => 'TLS'],
            ['name' => 'Australia', 'code' => 'AUS'],
            ['name' => 'New Zealand', 'code' => 'NZL'],
            ['name' => 'Fiji', 'code' => 'FJI'],
            ['name' => 'Papua New Guinea', 'code' => 'PNG'],
            ['name' => 'Solomon Islands', 'code' => 'SLB'],
            ['name' => 'Vanuatu', 'code' => 'VUT'],
            ['name' => 'Samoa', 'code' => 'WSM'],
            ['name' => 'Tonga', 'code' => 'TON'],
            ['name' => 'Kiribati', 'code' => 'KIR'],
            ['name' => 'Tuvalu', 'code' => 'TUV'],
            ['name' => 'Nauru', 'code' => 'NRU'],
            ['name' => 'Marshall Islands', 'code' => 'MHL'],
            ['name' => 'Palau', 'code' => 'PLW'],
            ['name' => 'Micronesia', 'code' => 'FSM'],
            ['name' => 'Guam', 'code' => 'GUM'],
            ['name' => 'Northern Mariana Islands', 'code' => 'MNP'],
            ['name' => 'American Samoa', 'code' => 'ASM'],
            ['name' => 'Cook Islands', 'code' => 'COK'],
            ['name' => 'Niue', 'code' => 'NIU'],
            ['name' => 'Tokelau', 'code' => 'TKL'],
            ['name' => 'Wallis and Futuna', 'code' => 'WLF'],
            ['name' => 'French Polynesia', 'code' => 'PYF'],
            ['name' => 'New Caledonia', 'code' => 'NCL'],
            ['name' => 'Guernsey', 'code' => 'GGY'],
            ['name' => 'Isle of Man', 'code' => 'IMN'],
            ['name' => 'Jersey', 'code' => 'JEY'],
            ['name' => 'British Indian Ocean Territory', 'code' => 'IOT'],
            ['name' => 'Cayman Islands', 'code' => 'CYM'],
            ['name' => 'Bermuda', 'code' => 'BMU'],
            ['name' => 'Turks and Caicos Islands', 'code' => 'TCA'],
            ['name' => 'British Virgin Islands', 'code' => 'VGB'],
            ['name' => 'Montserrat', 'code' => 'MSR'],
            ['name' => 'Anguilla', 'code' => 'AIA'],
            ['name' => 'Falkland Islands', 'code' => 'FLK'],
            ['name' => 'Gibraltar', 'code' => 'GIB'],
            ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'code' => 'SHN'],
            ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'SGS'],
            ['name' => 'Antarctica', 'code' => 'ATA'],
            ['name' => 'Greenland', 'code' => 'GRL'],
            ['name' => 'Faroe Islands', 'code' => 'FRO'],
            ['name' => 'Svalbard and Jan Mayen', 'code' => 'SJM'],
            ['name' => 'Saint Pierre and Miquelon', 'code' => 'SPM'],
            ['name' => 'Aruba', 'code' => 'ABW'],
            ['name' => 'Curacao', 'code' => 'CUW'],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'code' => 'BES'],
            ['name' => 'Sint Maarten', 'code' => 'SXM'],
            ['name' => 'Curacao', 'code' => 'CUW'],
            ['name' => 'Saint Martin', 'code' => 'MAF'],
            ['name' => 'Saint Barthélemy', 'code' => 'BLM']
        ];

        foreach ($countries as $country) {
            DB::table('countries')->insert([
                'id' => Str::uuid(),
                'name' => $country['name'],
                'code' => $country['code'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
